displayName=Better Chat Resizer
author=Shanktank
description=Resize chat box and private messages - no flicker!
tags=chat,chatbox,private,message,extend,resize,resizable,resizeable,scale,stretch,width,height,ui
version=0.4.1
plugins=brc.BetterResizableChatPlugin
build=standard