displayName=Chat Resizer
author=Shanktank
description=Change the size of the chat box and private message split. Supports resizable and fixed layouts.
tags=chat,chatbox,private,message,extend,resize,resizable,resizeable,scale,stretch,width,height,ui,better,fixed,hide,toggle
version=2.3.6
plugins=brc.ChatResizerPlugin
build=standard