displayName=Chat Resizer
author=Shanktank
description=Resize chat box and private messages - no flicker!
tags=chat,chatbox,private,message,extend,resize,resizable,resizeable,scale,stretch,width,height,ui,better
version=0.6.0
plugins=brc.BetterResizableChatPlugin
build=standard